name: go-testing
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup cross toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: go build all
      run: |
        go build ./...

  test-cross:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build
      uses: crazy-max/ghaction-xgo@v3
      env:
        GO111MODULE: on
      with:
        pkg: cmd/senstore
        xgo_version: latest
        go_version: 1.23
        dest: build
        prefix: senstore
        targets: linux/amd64,linux/arm64,darwin/arm64
        v: true
        x: true
        race: false
        ldflags: -s -w
        buildmode: default
        trimpath: true



  test-matrix:
    if: false
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - 'darwin-*'
          - linux-arm64
          - linux-amd64

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build go program
      id: cgo-action
      uses: go-cross/cgo-actions@v1
      with:
        dir: .
        packages: ./cmd/senstore/
        targets: ${{ matrix.targets }}

