name: go-testing
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup cross toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: go build all
      run: |
        go build ./...

  test-cross:
    strategy:
      matrix:
        target:
          - linux/amd64
          - linux/arm64
          - darwin/amd64
          - darwin/arm64
          - windows/*
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build
      uses: crazy-max/ghaction-xgo@v3
      with:
        pkg: cmd/senstore
        xgo_version: latest
        go_version: 1.23
        dest: build
        prefix: senstore-${{ matrix.target }}
        targets: ${{ matrix.target }}
        v: true
        x: false
        race: false
        ldflags: -s -w
        buildmode: default
        trimpath: true

